export const GOOD_CATEGORY = {
  APPLIANCES: "APPLIANCES",
  BATHROOM: "BATHROOM",
  GAMES: "GAMES",
  FASHION: "FASHION",
  FURNITURE: "FURNITURE",
  HOME: "HOME",
  KITCHEN: "KITCHEN",
  LIGHTING: "LIGHTING",
  TOOLS: "TOOLS",
} as const;

export type GoodCategory = typeof GOOD_CATEGORY[keyof typeof GOOD_CATEGORY];
